const config = {
  cardStyles: {
    minWidth: "200px",
    minHeight: "160px",
    padding: "5px 15px",
    boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)",
  },
  itemStyles: {
    margin: "0",
  },
  lastItemStyles: {
    marginBottom: "50px",
  },
  cardNameStyles: {
    margin: "5px 0 15px",
    fontWeight: "bold",
  },
  cardButtonsContainerStyles: {
    position: "absolute",
    left: "0",
    bottom: "0",
    margin: "0",
    padding: "0",
    width: "100%",
  },
  cardButtonNewItemStyles: {
    display: "inline-block",
    width: "48%",
    textAlign: "center",
    margin: "0 2% 0 0",
    padding: "5px 0",
    backgroundColor: "#c0eb75",
    cursor: "pointer",
  },
  cardButtonDeleteCardStyles: {
    display: "inline-block",
    width: "48%",
    textAlign: "center",
    margin: "0 0 0 2%",
    padding: "5px 0",
    backgroundColor: "#ffa8a8",
    cursor: "pointer",
  },
  buttonNewCardStyles: {
    position: "fixed",
    height: "50px",
    width: "50px",
    top: "10px",
    right: "10px",
    backgroundColor: "#c0eb75",
    textAlign: "center",
    lineHeight: "50px",
    cursor: "pointer",
    fontSize: "120%",
    boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)",
  },
  buttonChangeScreenStyles: {
    position: "fixed",
    height: "50px",
    width: "50px",
    top: "70px",
    right: "10px",
    backgroundColor: "#ffc078",
    textAlign: "center",
    lineHeight: "50px",
    cursor: "pointer",
    fontSize: "120%",
    boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)",
  },
  nextz: 42, // should be overwritten in app routine
};
